from typing import Protocol
import pandas as pd

class MarketDataProvider(Protocol):
    def candles(self,symbol:str,timeframe:str,start=None,end=None)->pd.DataFrame: ...

class EconomicCalendarProvider(Protocol):
    def events(self,start=None,end=None): ...

class BrokerExecutionProvider(Protocol):
    def place_order(self,symbol:str,side:str,qty:float,entry:float,stop:float,take_profit:float|None=None): ...
    def close_position(self,symbol:str): ...
