from enum import Enum

class State(str,Enum):
    WAITING="WAITING"; MACRO_ANALYSIS="MACRO_ANALYSIS"; WEEKLY_BIAS_FOUND="WEEKLY_BIAS_FOUND"
    SWING_TARGET_IDENTIFIED="SWING_TARGET_IDENTIFIED"; LIQUIDITY_MAPPED="LIQUIDITY_MAPPED"
    INDUCEMENT_DETECTED="INDUCEMENT_DETECTED"; LIQUIDITY_SWEEP_DETECTED="LIQUIDITY_SWEEP_DETECTED"
    STRUCTURE_SHIFT_DETECTED="STRUCTURE_SHIFT_DETECTED"; DISPLACEMENT_CONFIRMED="DISPLACEMENT_CONFIRMED"
    ENTRY_ZONE_IDENTIFIED="ENTRY_ZONE_IDENTIFIED"; RISK_VALIDATED="RISK_VALIDATED"; TRADE_SIGNAL="TRADE_SIGNAL"
    ORDER_PLACED="ORDER_PLACED"; POSITION_MANAGEMENT="POSITION_MANAGEMENT"; TRADE_COMPLETE="TRADE_COMPLETE"

class StateMachine:
    def __init__(self): self.state=State.WAITING
    def advance(self,next_state):
        states=list(State)
        if states.index(next_state)!=states.index(self.state)+1: raise ValueError("invalid state transition")
        self.state=next_state
