import {NextResponse} from "next/server";
import {gunzipSync} from "node:zlib";
const BASE="https://github.com/BudBudness/SMC-Agent-/releases/download/research-data";
const SUPA="https://prqbeocaycxqsremxvmb.supabase.co";
const KEY="sb_publishable_PVS7tsfzFOSwbRxfsv6plg_eK0nAynL";
const H={apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json"};
async function db(path:string,init:RequestInit={}){const r=await fetch(SUPA+"/rest/v1/"+path,{...init,headers:{...H,...((init.headers||{}) as Record<string,string>)},cache:"no-store"});const b=await r.text();if(!r.ok)throw Error("database "+r.status+": "+b);return b?JSON.parse(b):null}
async function rel(name:string){const r=await fetch(BASE+"/"+name,{cache:"no-store"});if(!r.ok)throw Error("release unavailable: "+name);return r}
async function canonical(){const [a,b]=await Promise.all([rel("EURUSD_research_report.json"),rel("EURUSD_MTF_dashboard.json.gz")]);return {report:await a.json(),mtf:JSON.parse(gunzipSync(Buffer.from(await b.arrayBuffer())).toString("utf8"))}}
function csv(buf:ArrayBuffer){const s=gunzipSync(Buffer.from(buf)).toString("utf8").trim();const lines=s.split(/\r?\n/);const h=lines.shift()!.split(",");return lines.map(x=>{const a=x.split(",");const o:any={};h.forEach((k,i)=>o[k]=a[i]);return o}).filter(x=>x.timestamp)}
function bench(events:any[],bars:any[]){const n=(re:RegExp)=>events.filter(e=>re.test(String(e.name||e.type))).length;const c=bars.map(x=>+x.close).filter(Number.isFinite);return {definitions:{event_count:"Canonical event count.",liquidity_event_count:"Liquidity/sweep observation count.",window_return:"Descriptive close-to-close change across replay window."},results:{events:events.length,liquidity_events:n(/liquidity|sweep/i),displacement_events:n(/displacement/i),fvg_events:n(/fvg/i),order_block_events:n(/order_block|orderblock/i),replay_bars:bars.length,window_return:c.length>1?c[c.length-1]/c[0]-1:0},limitations:["Descriptive only.","No predictive interpretation.","Based on the validated research release."]}}
export async function GET(req:Request){try{const q=new URL(req.url).searchParams,r=q.get("resource");if(r==="runs")return NextResponse.json(await db("smc_research_runs?select=*&order=created_at.desc"));if(r==="hypotheses")return NextResponse.json(await db("smc_hypotheses?select=*&order=created_at.desc"));if(r==="evidence")return NextResponse.json(await db("smc_evidence?select=*&order=created_at.desc"));const x=await canonical();return NextResponse.json({report:x.report,mtf:x.mtf,source:x.report.dataset||{}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Research data unavailable"},{status:503})}}
export async function POST(req:Request){try{const b=await req.json();if(b.action==="run"){const {report,mtf}=await canonical();const csvr=await rel("EURUSD_M1_dashboard.csv.gz");const bars=csv(await csvr.arrayBuffer());const replay=bars.slice(-Math.min(2000,bars.length)).map((x:any)=>({timestamp:x.timestamp,open:+x.open,high:+x.high,low:+x.low,close:+x.close}));const result={run_version:"1.0",instrument:b.instrument||"EURUSD",dataset:report.dataset,look_ahead_policy:report.look_ahead_policy||"confirmed swings only",mtf:mtf.timeframes||{},market_state:report.market_state||{},events:report.events||[],evidence:report.evidence||[],benchmarks:bench(report.events||[],replay),replay,analogue_research:report.analogue_research||{},lineage:[{stage:"release",artifact:"EURUSD_research_report.json"},{stage:"mtf",artifact:"EURUSD_MTF_dashboard.json.gz"},{stage:"replay",artifact:"EURUSD_M1_dashboard.csv.gz"}]};const run=(await db("smc_research_runs",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify({instrument:result.instrument,dataset:report.dataset?.source||"HistData EUR/USD M1",status:"COMPLETED",parameters:b,result,completed_at:new Date().toISOString()})}))[0];await db("smc_reports",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify({run_id:run.id,report:result})});return NextResponse.json({run,result})}if(b.action==="hypothesis")return NextResponse.json((await db("smc_hypotheses",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify(b.data)}))[0]);if(b.action==="evidence")return NextResponse.json((await db("smc_evidence",{method:"POST",headers:{"Prefer":"return=representation"},body:JSON.stringify(b.data)}))[0]);if(b.action==="report")return NextResponse.json(await db("smc_reports?select=*&run_id=eq."+encodeURIComponent(b.run_id)));return NextResponse.json({error:"Unknown action"},{status:400})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Research operation failed"},{status:500})}}